import { type Vec3, add, clamp, distance, dot, mul, normalize, sub } from '../math';
import type { BMesh } from '../mesh';
import type { Edge, Face, Vert } from '../mesh/types';

import { loopInwardDirection, miterOffset } from './region';

export interface BevelOptions {
  width?: number;
  segments?: number;
  /** Shrink the width so offsets never pass the midpoint of a neighbouring edge. */
  clampOverlap?: boolean;
}

export interface BevelResult {
  /** The chamfer strips and caps generated by the bevel. */
  faces: Face[];
  newVerts: Vert[];
}

type ProfileCache = Map<string, Vert[]>;

function cornerKey(faceId: number, vertId: number): string {
  return `${faceId}:${vertId}`;
}

/**
 * Edge bevel by corner offset.
 *
 * Every face adjacent to a beveled edge is offset inward along that edge and
 * mitered at its corners; the gap left along each beveled edge is filled with a
 * profile strip, and vertices where several chamfers meet are capped.
 *
 * Where a bevel terminates, the neighbouring unbeveled edge is split so the
 * chamfer lands on a real edge instead of leaving a crack. Fans that terminate
 * against three or more unbeveled edges can still close with a coplanar cap;
 * that limitation is tracked in TODO.txt.
 */
export function bevelEdges(
  mesh: BMesh,
  edges: readonly Edge[],
  options: BevelOptions = {},
): BevelResult {
  const beveled = edges.filter((edge) => mesh.edges.has(edge.id) && edge.loops.length === 2);
  if (beveled.length === 0) return { faces: [], newVerts: [] };

  mesh.computeNormals();

  const beveledIds = new Set(beveled.map((edge) => edge.id));
  const segments = Math.max(1, Math.floor(options.segments ?? 1));
  const width = resolveWidth(beveled, beveledIds, options);
  const newVerts: Vert[] = [];
  const profiles: ProfileCache = new Map();

  const affectedFaces = new Map<number, Face>();
  for (const edge of beveled) {
    for (const face of mesh.edgeFaces(edge)) affectedFaces.set(face.id, face);
  }

  const splitVerts = collectTerminationSplits(
    mesh,
    affectedFaces,
    beveledIds,
    width,
    newVerts,
  );
  const cornerPoint = computeCornerPoints(
    mesh,
    affectedFaces,
    beveledIds,
    splitVerts,
    width,
    newVerts,
  );

  const rebuilt = [...affectedFaces.values()].map((face) => ({
    ring: rebuildRing(mesh, face, cornerPoint, splitVerts, beveledIds),
    materialIndex: face.materialIndex,
    smooth: face.smooth,
  }));
  const strips = beveled.map((edge) => planStrip(edge, cornerPoint));
  const caps = planCaps(mesh, beveled, beveledIds, cornerPoint);

  const staleEdges = new Set<Edge>();
  for (const face of affectedFaces.values()) {
    for (const edge of mesh.faceEdges(face)) staleEdges.add(edge);
    mesh.removeFace(face);
  }

  for (const spec of rebuilt) {
    if (spec.ring.length < 3) continue;
    mesh.addFace(spec.ring, { materialIndex: spec.materialIndex, smooth: spec.smooth });
  }

  const created: Face[] = [];
  for (const strip of strips) {
    if (strip) created.push(...buildStrip(mesh, strip, segments, profiles, newVerts));
  }
  for (const cap of caps) {
    const ring = expandCapRing(cap, segments, profiles);
    if (ring.length < 3) continue;
    created.push(mesh.addFace(ring));
  }

  for (const edge of staleEdges) {
    if (mesh.edges.has(edge.id) && edge.loops.length === 0) mesh.removeEdge(edge);
  }
  mesh.removeLooseVerts();
  mesh.computeNormals();

  for (const face of created) if (mesh.faces.has(face.id)) face.selected = true;

  return { faces: created, newVerts };
}

/**
 * Where exactly one of a corner's two edges is beveled, the chamfer ends on the
 * other edge. Both faces sharing that edge must agree on where, so the request
 * is keyed by edge and endpoint and resolved to a single shared vertex.
 */
function collectTerminationSplits(
  mesh: BMesh,
  affectedFaces: Map<number, Face>,
  beveledIds: ReadonlySet<number>,
  width: number,
  newVerts: Vert[],
): Map<string, Vert> {
  const requests = new Map<string, { edge: Edge; from: Vert; travel: number }>();

  const request = (edge: Edge, from: Vert, travel: number) => {
    const key = `${edge.id}:${from.id}`;
    const existing = requests.get(key);
    if (existing) existing.travel = Math.max(existing.travel, travel);
    else requests.set(key, { edge, from, travel });
  };

  for (const face of [...affectedFaces.values()]) {
    for (const loop of mesh.faceLoops(face)) {
      const previousBeveled = beveledIds.has(loop.prev.edge.id);
      const nextBeveled = beveledIds.has(loop.edge.id);
      if (previousBeveled === nextBeveled) continue;

      if (nextBeveled) {
        const direction = normalize(sub(loop.prev.vert.co, loop.vert.co));
        request(loop.prev.edge, loop.vert, travelAlong(direction, loopInwardDirection(loop), width));
      } else {
        const direction = normalize(sub(loop.next.vert.co, loop.vert.co));
        request(
          loop.edge,
          loop.vert,
          travelAlong(direction, loopInwardDirection(loop.prev), width),
        );
      }
    }
  }

  const splits = new Map<string, Vert>();
  for (const [key, { edge, from, travel }] of requests) {
    const other = mesh.edgeOther(edge, from);
    const limited = clamp(travel, 0, distance(from.co, other.co) * 0.45);
    const vert = mesh.addVert(add(from.co, mul(normalize(sub(other.co, from.co)), limited)));
    splits.set(key, vert);
    newVerts.push(vert);
    for (const face of mesh.edgeFaces(edge)) affectedFaces.set(face.id, face);
  }

  return splits;
}

function computeCornerPoints(
  mesh: BMesh,
  affectedFaces: ReadonlyMap<number, Face>,
  beveledIds: ReadonlySet<number>,
  splitVerts: ReadonlyMap<string, Vert>,
  width: number,
  newVerts: Vert[],
): Map<string, Vert> {
  const cornerPoint = new Map<string, Vert>();

  for (const face of affectedFaces.values()) {
    for (const loop of mesh.faceLoops(face)) {
      const key = cornerKey(face.id, loop.vert.id);
      const previousBeveled = beveledIds.has(loop.prev.edge.id);
      const nextBeveled = beveledIds.has(loop.edge.id);

      if (previousBeveled && nextBeveled) {
        const offset = miterOffset(
          loopInwardDirection(loop.prev),
          loopInwardDirection(loop),
          width,
        );
        const vert = mesh.addVert(add(loop.vert.co, offset));
        cornerPoint.set(key, vert);
        newVerts.push(vert);
        continue;
      }

      if (nextBeveled) {
        const split = splitVerts.get(`${loop.prev.edge.id}:${loop.vert.id}`);
        if (split) cornerPoint.set(key, split);
        continue;
      }

      if (previousBeveled) {
        const split = splitVerts.get(`${loop.edge.id}:${loop.vert.id}`);
        if (split) cornerPoint.set(key, split);
        continue;
      }

      // Neither corner edge is beveled: the corner survives unless chamfers
      // arriving along both of its edges have already cut it away.
      const cutBefore = splitVerts.has(`${loop.prev.edge.id}:${loop.vert.id}`);
      const cutAfter = splitVerts.has(`${loop.edge.id}:${loop.vert.id}`);
      if (!(cutBefore && cutAfter)) cornerPoint.set(key, loop.vert);
    }
  }

  return cornerPoint;
}

/** How far along `direction` a line offset by `width` along `inward` is met. */
function travelAlong(direction: Vec3, inward: Vec3, width: number): number {
  return width / Math.max(dot(direction, inward), 0.2);
}

function resolveWidth(
  beveled: readonly Edge[],
  beveledIds: ReadonlySet<number>,
  options: BevelOptions,
): number {
  const requested = Math.max(1e-4, options.width ?? 0.1);
  if (options.clampOverlap === false) return requested;

  let limit = Infinity;
  for (const edge of beveled) {
    limit = Math.min(limit, distance(edge.v0.co, edge.v1.co) * 0.45);
    for (const vert of [edge.v0, edge.v1]) {
      for (const neighbour of vert.edges) {
        if (beveledIds.has(neighbour.id)) continue;
        limit = Math.min(limit, distance(neighbour.v0.co, neighbour.v1.co) * 0.45);
      }
    }
  }
  return Number.isFinite(limit) ? Math.min(requested, limit) : requested;
}

function rebuildRing(
  mesh: BMesh,
  face: Face,
  cornerPoint: ReadonlyMap<string, Vert>,
  splitVerts: ReadonlyMap<string, Vert>,
  beveledIds: ReadonlySet<number>,
): Vert[] {
  const ring: Vert[] = [];

  for (const loop of mesh.faceLoops(face)) {
    const corner = cornerPoint.get(cornerKey(face.id, loop.vert.id));
    if (corner) ring.push(corner);
    if (beveledIds.has(loop.edge.id)) continue;

    const near = splitVerts.get(`${loop.edge.id}:${loop.vert.id}`);
    const far = splitVerts.get(`${loop.edge.id}:${loop.next.vert.id}`);
    if (near) ring.push(near);
    if (far) ring.push(far);
  }

  return dedupeRing(ring);
}

function dedupeRing(ring: readonly Vert[]): Vert[] {
  const result: Vert[] = [];
  for (const vert of ring) {
    if (result.length > 0 && result[result.length - 1] === vert) continue;
    result.push(vert);
  }
  while (result.length > 1 && result[0] === result[result.length - 1]) result.pop();
  return result;
}

interface StripPlan {
  railStart: [Vert, Vert];
  railEnd: [Vert, Vert];
  cornerStart: Vert;
  cornerEnd: Vert;
  materialIndex: number;
  smooth: boolean;
}

function planStrip(
  edge: Edge,
  cornerPoint: ReadonlyMap<string, Vert>,
): StripPlan | null {
  const [near, far] = edge.loops;
  if (!near || !far) return null;

  const start = near.vert;
  const end = near.next.vert;

  const startNear = cornerPoint.get(cornerKey(near.face.id, start.id));
  const endNear = cornerPoint.get(cornerKey(near.face.id, end.id));
  const startFar = cornerPoint.get(cornerKey(far.face.id, start.id));
  const endFar = cornerPoint.get(cornerKey(far.face.id, end.id));
  if (!startNear || !endNear || !startFar || !endFar) return null;

  return {
    railStart: [startNear, startFar],
    railEnd: [endNear, endFar],
    cornerStart: start,
    cornerEnd: end,
    materialIndex: near.face.materialIndex,
    smooth: near.face.smooth,
  };
}

/**
 * Quadratic Bézier from one rail to the other with the original corner as the
 * control point, which rounds the chamfer once segments > 1.
 */
function profileRail(
  mesh: BMesh,
  from: Vert,
  to: Vert,
  corner: Vert,
  segments: number,
  profiles: ProfileCache,
  newVerts: Vert[],
): Vert[] {
  const key = `${from.id}:${to.id}:${corner.id}`;
  const cached = profiles.get(key);
  if (cached) return cached;

  const rail: Vert[] = [from];
  for (let i = 1; i < segments; i++) {
    const t = i / segments;
    const inverse = 1 - t;
    rail.push(
      mesh.addVert({
        x: inverse * inverse * from.co.x + 2 * inverse * t * corner.co.x + t * t * to.co.x,
        y: inverse * inverse * from.co.y + 2 * inverse * t * corner.co.y + t * t * to.co.y,
        z: inverse * inverse * from.co.z + 2 * inverse * t * corner.co.z + t * t * to.co.z,
      }),
    );
  }
  rail.push(to);

  for (let i = 1; i < rail.length - 1; i++) newVerts.push(rail[i]);
  profiles.set(key, rail);
  profiles.set(`${to.id}:${from.id}:${corner.id}`, [...rail].reverse());
  return rail;
}

function buildStrip(
  mesh: BMesh,
  plan: StripPlan,
  segments: number,
  profiles: ProfileCache,
  newVerts: Vert[],
): Face[] {
  const start = profileRail(
    mesh,
    plan.railStart[0],
    plan.railStart[1],
    plan.cornerStart,
    segments,
    profiles,
    newVerts,
  );
  const end = profileRail(
    mesh,
    plan.railEnd[0],
    plan.railEnd[1],
    plan.cornerEnd,
    segments,
    profiles,
    newVerts,
  );

  const faces: Face[] = [];
  for (let i = 0; i < segments; i++) {
    const ring = dedupeRing([end[i], start[i], start[i + 1], end[i + 1]]);
    if (ring.length < 3) continue;
    faces.push(mesh.addFace(ring, { materialIndex: plan.materialIndex, smooth: plan.smooth }));
  }
  return faces;
}

interface CapPlan {
  vert: Vert;
  entries: { corner: Vert; bridged: boolean }[];
}

function planCaps(
  mesh: BMesh,
  beveled: readonly Edge[],
  beveledIds: ReadonlySet<number>,
  cornerPoint: ReadonlyMap<string, Vert>,
): CapPlan[] {
  const candidates = new Map<number, Vert>();
  for (const edge of beveled) {
    candidates.set(edge.v0.id, edge.v0);
    candidates.set(edge.v1.id, edge.v1);
  }

  const caps: CapPlan[] = [];
  for (const vert of candidates.values()) {
    const fan = walkFan(mesh, vert);
    if (!fan) continue;

    const entries: CapPlan['entries'] = [];
    for (const step of fan) {
      const corner = cornerPoint.get(cornerKey(step.face.id, vert.id));
      if (!corner) continue;
      entries.push({ corner, bridged: beveledIds.has(step.exitEdge.id) });
    }
    if (entries.length < 3) continue;
    caps.push({ vert, entries });
  }
  return caps;
}

/**
 * Walks the closed fan of faces around a vertex, leaving each face through the
 * edge entering its corner. That direction is what orients the resulting cap
 * outward. Returns null for boundary or non-manifold fans, where no single cap
 * polygon exists.
 */
function walkFan(mesh: BMesh, vert: Vert): { face: Face; exitEdge: Edge }[] | null {
  const faces = mesh.vertFaces(vert);
  if (faces.length < 3) return null;
  for (const edge of vert.edges) {
    if (edge.loops.length !== 2) return null;
  }

  const start = faces[0];
  const walk: { face: Face; exitEdge: Edge }[] = [];
  let current = start;

  for (let guard = 0; guard <= faces.length; guard++) {
    const loop = mesh.loopOfVertInFace(current, vert);
    if (!loop) return null;
    const exitEdge = loop.prev.edge;
    walk.push({ face: current, exitEdge });

    const next = mesh.edgeFaces(exitEdge).find((face) => face !== current);
    if (!next) return null;
    if (next === start) return walk.length === faces.length ? walk : null;
    current = next;
  }
  return null;
}

function expandCapRing(cap: CapPlan, segments: number, profiles: ProfileCache): Vert[] {
  const ring: Vert[] = [];

  for (let i = 0; i < cap.entries.length; i++) {
    const entry = cap.entries[i];
    const next = cap.entries[(i + 1) % cap.entries.length];
    ring.push(entry.corner);

    if (!entry.bridged || segments < 2) continue;
    const rail = profiles.get(`${entry.corner.id}:${next.corner.id}:${cap.vert.id}`);
    if (!rail) continue;
    for (let step = 1; step < rail.length - 1; step++) ring.push(rail[step]);
  }

  return dedupeRing(ring);
}
