import {
  composeMatrix,
  createTransform,
  normalMatrix,
  normalize,
  radToDeg,
  transformDirection,
  transformPoint,
} from '../math';
import type { BMesh } from '../mesh';

import { prepareMesh } from './obj';
import {
  type ExportObject,
  type ExportOptions,
  convertDirection,
  convertPoint,
  resolveExportOptions,
  unitScaleFactor,
} from './types';

/**
 * ASCII FBX 7.4 (version 7400) writer.
 *
 * Three.js has no FBX exporter and the binary format is Autodesk's, so the
 * workable route is ASCII, which Unity, Unreal, Blender, Maya and 3ds Max all
 * import. Binary is a later optimisation, not a requirement.
 */

/** FBX object ids must be unique and non-zero; 0 is reserved for the scene root. */
let idCounter = 1_000_000;

function nextId(): number {
  idCounter += 1;
  return idCounter;
}

function num(value: number): string {
  if (!Number.isFinite(value)) return '0';
  return Number(value.toFixed(6)).toString();
}

function indent(depth: number): string {
  return '\t'.repeat(depth);
}

/** FBX ASCII arrays are `*count {` followed by a single `a:` row. */
function arrayNode(depth: number, name: string, values: readonly (number | string)[]): string[] {
  const pad = indent(depth);
  if (values.length === 0) {
    return [`${pad}${name}: *0 {`, `${pad}\ta: `, `${pad}}`];
  }

  const rows: string[] = [];
  const perRow = 12;
  for (let i = 0; i < values.length; i += perRow) {
    rows.push(values.slice(i, i + perRow).join(','));
  }

  return [`${pad}${name}: *${values.length} {`, `${pad}\ta: ${rows.join(`\n${pad}\t`)}`, `${pad}}`];
}

interface GeometryData {
  positions: number[];
  polygonVertexIndex: number[];
  normals: number[];
  uvs: number[];
  materials: number[];
}

function buildGeometry(mesh: BMesh, object: ExportObject, options: ExportOptions): GeometryData {
  const scale = options.scale * unitScaleFactor(options.unit);
  const transform = options.applyTransform ? object.transform : createTransform();
  const matrix = composeMatrix(transform);
  const normals = normalMatrix(transform);

  const positions: number[] = [];
  const vertIndex = new Map<number, number>();

  let index = 0;
  for (const vert of mesh.verts.values()) {
    const point = convertPoint(transformPoint(matrix, vert.co), options.upAxis, scale);
    positions.push(point.x, point.y, point.z);
    vertIndex.set(vert.id, index++);
  }

  const polygonVertexIndex: number[] = [];
  const normalValues: number[] = [];
  const uvs: number[] = [];
  const materials: number[] = [];

  for (const face of mesh.faces.values()) {
    const loops = mesh.faceLoops(face);
    materials.push(Math.max(0, face.materialIndex));

    loops.forEach((loop, position) => {
      const vertex = vertIndex.get(loop.vert.id) ?? 0;
      // The last index of every polygon is encoded as -(index + 1). Without
      // this the importer cannot tell where one polygon ends and the next
      // begins, and the whole mesh comes in as garbage.
      polygonVertexIndex.push(position === loops.length - 1 ? -(vertex + 1) : vertex);

      const source = options.perVertexNormals && face.smooth ? loop.vert.normal : face.normal;
      const direction = convertDirection(
        normalize(transformDirection(normals, source)),
        options.upAxis,
      );
      normalValues.push(direction.x, direction.y, direction.z);
      uvs.push(loop.uv.u, loop.uv.v);
    });
  }

  return { positions, polygonVertexIndex, normals: normalValues, uvs, materials };
}

export function exportFBXAscii(
  objects: readonly ExportObject[],
  options: Partial<ExportOptions> = {},
): string {
  const resolved = resolveExportOptions(options);
  const now = new Date();

  const entries = objects.map((object) => {
    const mesh = prepareMesh(object, resolved);
    return {
      object,
      mesh,
      data: buildGeometry(mesh, object, resolved),
      geometryId: nextId(),
      modelId: nextId(),
      materialIds: object.materials.map(() => nextId()),
    };
  });

  const materialCount = entries.reduce((total, entry) => total + entry.materialIds.length, 0);
  const lines: string[] = [];

  lines.push(
    '; FBX 7.4.0 project file',
    '; Generated by 3DOO',
    '; ----------------------------------------------------',
    '',
    'FBXHeaderExtension:  {',
    '\tFBXHeaderVersion: 1003',
    '\tFBXVersion: 7400',
    '\tCreationTimeStamp:  {',
    '\t\tVersion: 1000',
    `\t\tYear: ${now.getFullYear()}`,
    `\t\tMonth: ${now.getMonth() + 1}`,
    `\t\tDay: ${now.getDate()}`,
    `\t\tHour: ${now.getHours()}`,
    `\t\tMinute: ${now.getMinutes()}`,
    `\t\tSecond: ${now.getSeconds()}`,
    '\t\tMillisecond: 0',
    '\t}',
    '\tCreator: "3DOO"',
    '}',
  );

  lines.push(...globalSettings(resolved));

  lines.push(
    'Definitions:  {',
    '\tVersion: 100',
    `\tCount: ${1 + entries.length * 2 + materialCount}`,
    '\tObjectType: "GlobalSettings" {',
    '\t\tCount: 1',
    '\t}',
    '\tObjectType: "Geometry" {',
    `\t\tCount: ${entries.length}`,
    '\t}',
    '\tObjectType: "Model" {',
    `\t\tCount: ${entries.length}`,
    '\t}',
  );
  if (materialCount > 0) {
    lines.push('\tObjectType: "Material" {', `\t\tCount: ${materialCount}`, '\t}');
  }
  lines.push('}', '');

  lines.push('Objects:  {');
  for (const entry of entries) {
    lines.push(...geometryNode(entry.geometryId, entry.object.name, entry.data));
    lines.push(...modelNode(entry.modelId, entry.object, resolved));
    entry.object.materials.forEach((material, index) => {
      lines.push(...materialNode(entry.materialIds[index], material.name, material.color));
    });
  }
  lines.push('}', '');

  lines.push('Connections:  {');
  for (const entry of entries) {
    lines.push(
      `\t;Model::${entry.object.name}, Model::RootNode`,
      `\tC: "OO",${entry.modelId},0`,
      '',
      `\t;Geometry::, Model::${entry.object.name}`,
      `\tC: "OO",${entry.geometryId},${entry.modelId}`,
      '',
    );
    entry.object.materials.forEach((material, index) => {
      lines.push(
        `\t;Material::${material.name}, Model::${entry.object.name}`,
        `\tC: "OO",${entry.materialIds[index]},${entry.modelId}`,
        '',
      );
    });
  }
  lines.push('}', '');

  return lines.join('\n');
}

function globalSettings(options: ExportOptions): string[] {
  // FBX names axes by index: 0 = X, 1 = Y, 2 = Z.
  const upAxis = options.upAxis === 'z' ? 2 : 1;
  const frontAxis = options.upAxis === 'z' ? 1 : 2;

  return [
    'GlobalSettings:  {',
    '\tVersion: 1000',
    '\tProperties70:  {',
    `\t\tP: "UpAxis", "int", "Integer", "",${upAxis}`,
    '\t\tP: "UpAxisSign", "int", "Integer", "",1',
    `\t\tP: "FrontAxis", "int", "Integer", "",${frontAxis}`,
    '\t\tP: "FrontAxisSign", "int", "Integer", "",1',
    '\t\tP: "CoordAxis", "int", "Integer", "",0',
    '\t\tP: "CoordAxisSign", "int", "Integer", "",1',
    `\t\tP: "OriginalUpAxis", "int", "Integer", "",${upAxis}`,
    '\t\tP: "OriginalUpAxisSign", "int", "Integer", "",1',
    '\t\tP: "UnitScaleFactor", "double", "Number", "",1',
    '\t\tP: "OriginalUnitScaleFactor", "double", "Number", "",1',
    '\t}',
    '}',
    '',
  ];
}

function geometryNode(id: number, name: string, data: GeometryData): string[] {
  const lines: string[] = [`\tGeometry: ${id}, "Geometry::${name}", "Mesh" {`];

  lines.push(...arrayNode(2, 'Vertices', data.positions.map(num)));
  lines.push(...arrayNode(2, 'PolygonVertexIndex', data.polygonVertexIndex));
  lines.push('\t\tGeometryVersion: 124');

  lines.push(
    '\t\tLayerElementNormal: 0 {',
    '\t\t\tVersion: 102',
    '\t\t\tName: ""',
    '\t\t\tMappingInformationType: "ByPolygonVertex"',
    '\t\t\tReferenceInformationType: "Direct"',
  );
  lines.push(...arrayNode(3, 'Normals', data.normals.map(num)));
  lines.push('\t\t}');

  lines.push(
    '\t\tLayerElementUV: 0 {',
    '\t\t\tVersion: 101',
    '\t\t\tName: "UVMap"',
    '\t\t\tMappingInformationType: "ByPolygonVertex"',
    '\t\t\tReferenceInformationType: "Direct"',
  );
  lines.push(...arrayNode(3, 'UV', data.uvs.map(num)));
  lines.push('\t\t}');

  lines.push(
    '\t\tLayerElementMaterial: 0 {',
    '\t\t\tVersion: 101',
    '\t\t\tName: ""',
    '\t\t\tMappingInformationType: "ByPolygon"',
    '\t\t\tReferenceInformationType: "IndexToDirect"',
  );
  lines.push(...arrayNode(3, 'Materials', data.materials));
  lines.push('\t\t}');

  lines.push(
    '\t\tLayer: 0 {',
    '\t\t\tVersion: 100',
    '\t\t\tLayerElement:  {',
    '\t\t\t\tType: "LayerElementNormal"',
    '\t\t\t\tTypedIndex: 0',
    '\t\t\t}',
    '\t\t\tLayerElement:  {',
    '\t\t\t\tType: "LayerElementMaterial"',
    '\t\t\t\tTypedIndex: 0',
    '\t\t\t}',
    '\t\t\tLayerElement:  {',
    '\t\t\t\tType: "LayerElementUV"',
    '\t\t\t\tTypedIndex: 0',
    '\t\t\t}',
    '\t\t}',
    '\t}',
  );

  return lines;
}

function modelNode(id: number, object: ExportObject, options: ExportOptions): string[] {
  // Baking the transform into the vertices leaves the node at the origin.
  const transform = options.applyTransform ? createTransform() : object.transform;
  const scale = options.scale * unitScaleFactor(options.unit);
  const translation = convertPoint(transform.position, options.upAxis, scale);
  const rotation = convertDirection(
    {
      x: radToDeg(transform.rotation.x),
      y: radToDeg(transform.rotation.y),
      z: radToDeg(transform.rotation.z),
    },
    options.upAxis,
  );

  return [
    `\tModel: ${id}, "Model::${object.name}", "Mesh" {`,
    '\t\tVersion: 232',
    '\t\tProperties70:  {',
    '\t\t\tP: "InheritType", "enum", "", "",1',
    `\t\t\tP: "Lcl Translation", "Lcl Translation", "", "A",${num(translation.x)},${num(translation.y)},${num(translation.z)}`,
    `\t\t\tP: "Lcl Rotation", "Lcl Rotation", "", "A",${num(rotation.x)},${num(rotation.y)},${num(rotation.z)}`,
    `\t\t\tP: "Lcl Scaling", "Lcl Scaling", "", "A",${num(transform.scale.x)},${num(transform.scale.y)},${num(transform.scale.z)}`,
    '\t\t\tP: "DefaultAttributeIndex", "int", "Integer", "",0',
    '\t\t}',
    '\t\tShading: T',
    '\t\tCulling: "CullingOff"',
    '\t}',
  ];
}

function materialNode(
  id: number,
  name: string,
  color: { r: number; g: number; b: number },
): string[] {
  return [
    `\tMaterial: ${id}, "Material::${name}", "" {`,
    '\t\tVersion: 102',
    '\t\tShadingModel: "phong"',
    '\t\tMultiLayer: 0',
    '\t\tProperties70:  {',
    '\t\t\tP: "ShadingModel", "KString", "", "", "phong"',
    `\t\t\tP: "DiffuseColor", "Color", "", "A",${num(color.r)},${num(color.g)},${num(color.b)}`,
    `\t\t\tP: "Diffuse", "Vector3D", "Vector", "",${num(color.r)},${num(color.g)},${num(color.b)}`,
    '\t\t\tP: "SpecularColor", "Color", "", "A",0,0,0',
    '\t\t\tP: "Shininess", "double", "Number", "",20',
    '\t\t\tP: "Opacity", "double", "Number", "",1',
    '\t\t}',
    '\t}',
  ];
}
